// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()  // Google's Maven repository
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.10.0'
        classpath 'com.google.gms:google-services:4.4.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.0'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.3'
    }
}

plugins {
    id 'com.google.devtools.ksp' version "2.1.0-1.0.29" apply false
}

allprojects {
    repositories {
        google()  // Google's Maven repository
        mavenCentral()
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}